services:
    root:
      build:
        context: .
      working_dir: /app
      volumes:
        - ./:/app
        - /app/node_modules
      ports:
        - "${CLIENT_PORT}:${CLIENT_PORT}"
        - "${SERVER_PORT}:${SERVER_PORT}"
      env_file:
        - .env
      command: yarn dev
      tty: true
