services:
    root:
      build:
        context: .
      working_dir: /app
      volumes:
        - ./:/app
        - /app/node_modules
      env_file:
        - .env
      tty: true

    server:
      build:
        context: './server'
      working_dir: /server
      volumes:
        - ./server:/server
        - ./common:/common
        - /server/node_modules
        - ./tsconfig.json:/tsconfig.json:ro
      ports:
        - "${SERVER_PORT}:${SERVER_PORT}"
      env_file:
        - .env
      command: yarn dev
      depends_on: 
        - root

    client:
      build:
        context: './client'
      working_dir: /client
      depends_on: 
        - server
      volumes:
        - ./client:/client
        - /client/node_modules
        - ./common:/common
        - ./tsconfig.json:/tsconfig.json:ro
      ports:
        - "${CLIENT_PORT}:${CLIENT_PORT}"
      env_file:
        - .env
      command: yarn dev
