services:
    root:
      image: node:22
      working_dir: /app
      volumes:
        - ./:/app
      tty: true

    server:
      image: node:22
      working_dir: /server
      depends_on: 
        - root
      tty: true
      volumes:
        - ./tsconfig.json:/tsconfig.json:ro
      # command: yarn dev

    client:
      image: node:22
      working_dir: /client
      depends_on: 
        - root
      tty: true
      volumes:
        - ./tsconfig.json:/tsconfig.json:ro
      # command: yarn dev
